apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: django-tutorial
  labels:
    app: mariadb
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: mariadb
    tier: backend
  ports:
  - port: 3306
    targetPort: mysql-server
