# Generated by Django 4.2 on 2025-12-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
